spring.application.name=labreserve
server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/labreserve}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.timezone.default_storage=NORMALIZE_UTC
spring.jpa.open-in-view=false

spring.jackson.time-zone=America/Lima
spring.jackson.serialization.write-dates-as-timestamps=false

jwt.secret=${JWT_SECRET:labreserve-utec-dbp-2026-super-secret-key-change-me-please-1234567890}
jwt.expiration-access=3600000
